import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {randomUUID,createHash} from 'node:crypto';import {PGlite} from '@electric-sql/pglite';import {createStatisticsModel} from '../web/statistics-model.js';
test('管理员成员投影：权限、隔离、只读、历史完整、空成员、分页及审计',async()=>{
 const db=new PGlite(),admin=randomUUID(),a=randomUUID(),b=randomUUID(),empty=randomUUID(),ha=randomUUID(),hb=randomUUID(),deleted=randomUUID(),hash=createHash('sha256').update('grant').digest('hex');
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,banned_until timestamptz,created_at timestamptz default now());create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;`);
 for(const [id,email] of [[admin,'admin@example.test'],[a,'a@example.test'],[b,'b@example.test'],[empty,'empty@example.test']])await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[id,email]);
 for(const name of ['202610040002_habits.sql','202610040003_statistics.sql','202610050005_admin_sessions.sql','202610050006_admin_members.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));
 await db.query("insert into habitify_admin.principals(user_id,expected_email) values($1,'admin@example.test')",[admin]);
 await db.query("insert into public.habit_profiles(user_id,timezone) values($1,'Australia/Sydney'),($2,'America/Los_Angeles')",[a,b]);
 for(const [id,uid,name,archived,del] of [[ha,a,'A专属',true,null],[hb,b,'B专属',false,null],[deleted,a,'已删除',false,new Date().toISOString()]])await db.query("insert into public.habits(id,user_id,name,kind,goal,unit,icon,position,start_day,note,archived,deleted_at) values($1,$2,$3,'quantity',8,'杯','water',0,'2026-09-01','私人备注',$4,$5)",[id,uid,name,archived,del]);
 await db.query("insert into public.habit_records(habit_id,user_id,day,goal,progress) values($1,$2,'2026-09-01',8,8),($3,$4,'2026-09-02',8,2),($5,$2,'2026-09-02',8,8)",[ha,a,hb,b,deleted]);
 async function rpc(sql,args){await db.exec('set role service_role');try{return(await db.query(sql,args)).rows[0].data;}finally{await db.exec('reset role');}}
 const list=()=>rpc('select public.admin_members($1,$2,1,\'\') as data',[a,hash]);
 await assert.rejects(list(),/ADMIN_SESSION_EXPIRED/);await rpc('select public.admin_session_open($1,$2,$3) as data',[a,admin,hash]);
 const profilesBefore=(await db.query('select count(*)::int as n from public.habit_profiles')).rows[0].n;
 const all=await list();assert.equal(all.total,3);assert.equal(all.members.some(m=>m.id===admin),false);assert.deepEqual(Object.keys(all.members[0]).sort(),['confirmed','createdAt','email','enabled','id','timezone']);
 const read=id=>rpc('select public.admin_member_statistics($1,$2,$3) as data',[a,hash,id]);
 const sa=await read(a),sb=await read(b),se=await read(empty);assert.equal(sa.snapshot.timezone,'Australia/Sydney');assert.equal(sb.snapshot.timezone,'America/Los_Angeles');assert.equal(sa.member.id,a);assert.equal(sb.member.id,b);assert.equal(sa.snapshot.statistics.habits.some(h=>h.id===hb),false);assert.equal(sb.snapshot.statistics.habits.some(h=>h.id===ha),false);assert.deepEqual(Object.keys(sa.snapshot).sort(),['records','serverTime','statistics','timezone','today']);assert.equal(JSON.stringify(sa).includes('私人备注'),false);assert.equal(se.member.timezone,null);assert.equal(se.snapshot.timezone,'UTC');assert.equal(se.snapshot.statistics.habits.length,0);assert.equal((await db.query('select count(*)::int as n from public.habit_profiles')).rows[0].n,profilesBefore);assert.equal((await db.query('select count(*)::int as n from public.coin_ledger')).rows[0].n,0);
 const model=createStatisticsModel(sa.snapshot);assert.equal(model.period('all').count,2);assert.equal(model.period('all').list.some(x=>x.habit.deleted),false);
 await assert.rejects(read(admin),/MEMBER_NOT_FOUND/);await assert.rejects(read(randomUUID()),/MEMBER_NOT_FOUND/);await assert.rejects(rpc('select public.admin_member_statistics($1,$2,$3) as data',[b,hash,a]),/ADMIN_SESSION_EXPIRED/);
 const found=await rpc('select public.admin_members($1,$2,1,$3) as data',[a,hash,'A@']);assert.equal(found.total,1);assert.equal(found.members[0].id,a);assert.equal((await rpc('select public.admin_members($1,$2,1,$3) as data',[a,hash,'%'])).total,0);
 for(let i=0;i<22;i++)await db.query('insert into auth.users(id,email) values($1,$2)',[randomUUID(),`extra${i}@example.test`]);const p1=await list(),p2=await rpc('select public.admin_members($1,$2,2,\'\') as data',[a,hash]);assert.equal(p1.members.length,20);assert.equal(p2.members.length,5);assert.equal(new Set([...p1.members,...p2.members].map(m=>m.id)).size,25);
 for(const role of ['anon','authenticated']){await db.exec('set role '+role);try{await assert.rejects(db.query('select public.admin_members($1,$2,1,\'\')',[a,hash]),/permission denied/);await assert.rejects(db.query('select public.admin_member_statistics($1,$2,$3)',[a,hash,b]),/permission denied/);}finally{await db.exec('reset role');}}
 const audit=(await db.query("select target_id from habitify_admin.audit where operation='member_statistics_read'")).rows;assert.ok(audit.some(x=>x.target_id===b));await db.exec('update habitify_admin.principals set enabled=false');await assert.rejects(read(b),/ADMIN_FORBIDDEN/);
 }finally{await db.close();}
});
