import test from 'node:test';import assert from 'node:assert/strict';import {createAdminHandler,tokenHash} from '../supabase/functions/admin/handler.js';
const origin='https://billwang2002.github.io';
function fixture(extra={}){const calls=[];const handler=createAdminHandler({verifyRequester:async token=>token==='ordinary' ? 'caller-id' : null,reserveAttempt:async uid=>{calls.push(uid);return {adminId:'caller-id',email:'private@example.test'};},authenticate:async(i,p)=>p==='test-password',issue:async(u,a,h)=>{calls.push({u,a,h});return{expiresAt:'2030-01-01T00:00:00Z'};},check:async()=>({expiresAt:'2030-01-01T00:00:00Z'}),close:async()=>({closed:true}),...extra});return{handler,calls};}
const req=(p,headers={})=>new Request('https://example.test/admin',{method:'POST',headers:{Origin:origin,Authorization:'Bearer ordinary','Content-Type':'application/json',...headers},body:JSON.stringify(p)});
test('密码校验在服务端，会话为随机opaque标识，响应无邮箱/密码/Auth令牌',async()=>{const f=fixture();const r=await f.handler(req({op:'login',password:'test-password'}));assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');const result=await r.json();assert.deepEqual(Object.keys(result.data).sort(),['expiresAt','sessionToken']);assert.match(result.data.sessionToken,/^[0-9a-f]{64}$/);assert.equal(f.calls[1].h,await tokenHash(result.data.sessionToken));assert.equal(JSON.stringify(result).includes('private@'),false);assert.equal(JSON.stringify(result).includes('test-password'),false);});
test('匿名/伪造身份/跨来源/额外角色字段/错误密码拒绝，内部异常不回显',async()=>{const f=fixture();assert.equal((await f.handler(req({op:'login',password:'test-password'},{Authorization:''}))).status,401);assert.equal((await f.handler(req({op:'login',password:'test-password'},{Authorization:'Bearer fake'}))).status,401);assert.equal((await f.handler(req({op:'login',password:'test-password'},{Origin:'https://evil.test'}))).status,403);assert.equal((await f.handler(req({op:'login',password:'test-password',email:'x',isAdmin:true}))).status,422);const wrong=await f.handler(req({op:'login',password:'wrong'}));assert.equal(wrong.status,401);assert.equal((await wrong.json()).code,'ADMIN_PASSWORD_INVALID');const broken=fixture({authenticate:async()=>{throw new Error('private data');}});assert.deepEqual(await(await broken.handler(req({op:'login',password:'test-password'}))).json(),{code:'BACKEND_ERROR'});});
test('限流先于密码校验；缺失会话与超大正文拒绝',async()=>{let count=0;const f=fixture({reserveAttempt:async()=>({code:'ADMIN_RATE_LIMITED'}),authenticate:async()=>{count++;return true;}});assert.equal((await f.handler(req({op:'login',password:'test-password'}))).status,429);assert.equal(count,0);assert.equal((await f.handler(req({op:'verify'}))).status,401);assert.equal((await f.handler(req({op:'login',password:'x'.repeat(5000)}))).status,422);});
test('成员读取严格限制操作和参数，每次携带绑定会话哈希，拒绝跨账户伪造',async()=>{
 const calls=[],f=fixture({members:async(u,h,page,search)=>{calls.push({u,h,page,search});return{members:[],total:0,page,pageSize:20};},memberStatistics:async(u,h,id)=>{calls.push({u,h,id});return{member:{id},snapshot:{}};}}),token='b'.repeat(64),headers={'X-Admin-Session':token},id='00000000-0000-4000-8000-000000000001';
 assert.equal((await f.handler(req({op:'members',page:1,search:''}))).status,401);
 assert.equal((await f.handler(req({op:'members',page:1,search:''},headers))).status,200);assert.deepEqual(calls[0],{u:'caller-id',h:await tokenHash(token),page:1,search:''});
 assert.equal((await f.handler(req({op:'member-statistics',memberId:id},headers))).status,200);assert.equal(calls[1].id,id);
 for(const payload of [{op:'members',page:0,search:''},{op:'members',page:1,search:'',isAdmin:true},{op:'member-statistics',memberId:'bad'},{op:'member-statistics',memberId:id,userId:'other'},{op:'delete-member',memberId:id}])assert.equal((await f.handler(req(payload,headers))).status,422);
 const expired=fixture({members:async()=>{throw new Error('ADMIN_SESSION_EXPIRED');}});assert.equal((await expired.handler(req({op:'members',page:1,search:''},headers))).status,401);
});

test('普通成员即使提交正确后台密码也不能进入，且不执行密码认证或发放会话',async()=>{let authenticated=0,issued=0;const f=fixture({reserveAttempt:async()=>({adminId:'other-admin',email:'private@example.test'}),authenticate:async()=>{authenticated++;return true;},issue:async()=>{issued++;}});const response=await f.handler(req({op:'login',password:'test-password'}));assert.equal(response.status,403);assert.deepEqual(await response.json(),{code:'ADMIN_FORBIDDEN'});assert.equal(authenticated,0);assert.equal(issued,0);});
test('成员管理接口严格参数和会话授权，密码错误不回显',async()=>{
 const id='00000000-0000-4000-8000-000000000001',rid='00000000-0000-4000-8000-000000000002',token='a'.repeat(64),calls=[];
 const f=fixture({memberWrite:async(u,h,p)=>{calls.push({u,h,p});return {completed:true};},memberCoins:async(u,h,p)=>{calls.push({u,h,p});return {completed:true};}}),headers={'X-Admin-Session':token};
 const create={op:'member-create',requestId:rid,email:'new@example.test',password:'test-password'};
 assert.equal((await f.handler(req(create))).status,401);assert.equal(calls.length,0);
 assert.equal((await f.handler(req(create,headers))).status,200);assert.equal(calls[0].h,await tokenHash(token));
 for(const invalid of [{...create,role:'admin'},{...create,password:'short'},{...create,email:'bad'},{op:'member-delete',memberId:id,requestId:rid},{op:'member-coins',memberId:id,requestId:rid,balance:-1,expectedBalance:0,reason:'x'},{op:'member-coins',memberId:id,requestId:rid,balance:10,expectedBalance:0,reason:''}])assert.ok((await f.handler(req(invalid,headers))).status>=400);
 const forbidden=fixture({memberWrite:async()=>{throw new Error('ADMIN_FORBIDDEN');}});assert.equal((await forbidden.handler(req(create,headers))).status,403);
});
