import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';import {PGlite} from '@electric-sql/pglite';
test('外观SQL：本人隔离、默认不建资料、幂等、并发拒绝、旧JWT拒绝及账号删除级联',async()=>{
 const db=new PGlite(),a=randomUUID(),b=randomUUID();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,banned_until timestamptz,created_at timestamptz default now());create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql as $$select jsonb_build_object('iat',nullif(current_setting('request.jwt.claim.iat',true),'')::bigint)$$;grant usage on schema auth to anon,authenticated;`);
 await db.query('insert into auth.users(id,email) values($1,$2),($3,$4)',[a,'a@example.test',b,'b@example.test']);
 for(const f of ['202610030001_infrastructure.sql','202610040002_habits.sql','202610040003_statistics.sql','202610040004_delete_confirmation.sql','202610050005_admin_sessions.sql','202610050006_admin_members.sql','202610100007_admin_identity.sql','202610100008_admin_member_management.sql','202610100009_appearance.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
 async function rpc(p,uid=a,iat=100){await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.iat',$2,false)",[uid,String(iat)]);await db.exec('set role authenticated');try{return(await db.query('select public.appearance_request($1::jsonb) as data',[JSON.stringify(p)])).rows[0].data;}finally{await db.exec('reset role');}}
 const start=await rpc({op:'appearance-get'});assert.equal(start.revision,0);assert.equal((await db.query('select count(*)::int as n from public.habit_profiles')).rows[0].n,0);
 const p={op:'appearance-set',settings:{theme:'lumi',background:'garden',surface:'glass',avatar:'lumi',mode:'dark'},expectedRevision:0,requestId:randomUUID()};const saved=await rpc(p);assert.equal(saved.revision,1);assert.deepEqual(await rpc(p),saved);assert.equal((await rpc({op:'appearance-get'},b)).settings.theme,'growth');
 await assert.rejects(rpc({...p,requestId:randomUUID()}),/STALE_DATA/);await assert.rejects(rpc({...p,settings:{...p.settings,mode:'light'}}),/REQUEST_REUSED/);
 await assert.rejects(rpc({...p,userId:b}),/INVALID_REQUEST/);await assert.rejects(rpc({...p,requestId:randomUUID(),settings:{...p.settings,background:'https://evil.test'}}),/INVALID_REQUEST/);
 await db.exec('set role authenticated');await assert.rejects(db.query('select * from public.account_appearance'),/permission denied/);await db.exec('reset role');await db.exec('set role anon');await assert.rejects(db.query("select public.appearance_request('{\"op\":\"appearance-get\"}')"),/permission denied/);await db.exec('reset role');
 await db.query('insert into habitify_admin.member_access(user_id,revoked_before) values($1,100)',[a]);await assert.rejects(rpc({op:'appearance-get'}),/LOGIN_REQUIRED/);assert.equal((await rpc({op:'appearance-get'},a,101)).revision,1);
 await db.query('delete from auth.users where id=$1',[a]);assert.equal((await db.query('select count(*)::int as n from public.account_appearance')).rows[0].n,0);
 }finally{await db.close();}
});
