import {createMemberEditor,memberDialogHtml} from './admin-member-form.js';
import {iconSvg} from './theme.js';
import {createStatistics} from './statistics.js';
const esc=value=>String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const joined=value=>value ? new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium'}).format(new Date(value)) : '—';
export function createAdminMembers(root,{api,onInvalid=()=>{}}){
 root.innerHTML=`<section class="admin-members-panel detail-panel"><div class="stats-heading"><h2>成员</h2><div class="admin-members-toolbar"><button data-add class="admin-add-member" type="button">新增成员</button><button data-refresh class="admin-icon-button" type="button" aria-label="刷新成员列表" title="刷新列表">${iconSvg('refresh')}</button></div></div><form data-search-form class="admin-search" novalidate><label for="admin-member-search">搜索成员邮箱</label><div><input id="admin-member-search" data-search maxlength="100" placeholder="输入邮箱关键词" autocomplete="off"><button type="submit">搜索</button></div></form><p data-message class="account-feedback" role="status"></p><p data-operation-message class="account-feedback" role="status"></p><div data-pending class="admin-pending-writes" hidden></div><div data-members class="account-list"></div><div class="admin-pagination"><button data-prev type="button">上一页</button><span data-page-label></span><button data-next type="button">下一页</button></div></section><section data-detail hidden><div class="detail-panel admin-member-identity"><div class="stats-heading"><h2>成员打卡统计</h2><button data-toggle class="admin-icon-button admin-statistics-toggle" type="button" aria-label="收起成员统计" aria-expanded="true" aria-controls="admin-member-statistics-body"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m7 9 5 6 5-6Z"/></svg></button></div><div data-identity></div><div data-actions class="admin-member-actions" hidden><button data-password type="button">修改密码</button><button data-coins type="button">调整金币</button><button data-delete class="danger-text" type="button">删除账号</button></div></div><div id="admin-member-statistics-body" data-detail-body><p data-detail-message class="account-feedback" role="status"></p><div data-statistics-root></div></div></section>${memberDialogHtml()}`;
 const $=key=>root.querySelector(`[data-${key}]`),stats=createStatistics($('statistics-root'),{readOnly:true,showHeading:false});
 const editor=createMemberEditor(root,{api,onSaved:(mode,id)=>{ $('operation-message').textContent={create:'成员账号已创建。',password:'密码已修改，成员需重新登录。',delete:'成员账号及个人数据已永久删除。',coins:'金币余额已调整。'}[mode];if(mode==='delete' || mode==='create')void load();else void select(id);},onInvalid});
 let currentMember=null;
 let epoch=0,listSequence=0,detailSequence=0,page=1,search='',selected=null,visible=false,loading=false;
 function setExpanded(expanded){$('detail-body').hidden=!expanded;$('toggle').setAttribute('aria-expanded',String(expanded));$('toggle').setAttribute('aria-label',expanded ? '收起成员统计' : '展开成员统计');}
 function clearDetail(){setExpanded(true);++detailSequence;selected=null;currentMember=null;$('actions').hidden=true;stats.clear();$('identity').replaceChildren();$('detail-message').textContent='';$('detail').hidden=true;$('members').querySelectorAll('[data-member]').forEach(b=>b.setAttribute('aria-pressed','false'));}
 function invalid(error){if(!api.active()){clear();onInvalid(error);return true;}return false;}
 function controls(total=0){$('prev').disabled=loading || page<=1;$('next').disabled=loading || page*20>=total;$('refresh').disabled=loading;}
 async function load(){if(!visible || !api.active())return;const ticket=epoch,seq=++listSequence;loading=true;controls();$('members').replaceChildren();clearDetail();$('page-label').textContent='';$('message').textContent='正在读取成员…';
  try{const data=await api.members(page,search);if(ticket!==epoch || seq!==listSequence || !visible)return;
   if(data.page!==page || !Array.isArray(data.members))throw new Error('成员列表响应不完整，请重试。');
   $('message').textContent=data.total ? `共 ${data.total} 位成员` : '暂无匹配的成员。';$('page-label').textContent=`第 ${page} / ${Math.max(1,Math.ceil(data.total/20))} 页`;
   $('members').innerHTML=data.members.map(m=>`<button type="button" data-member="${esc(m.id)}" class="account-row admin-member-row"><span class="account-row-copy"><strong>${esc(m.email)}</strong><small>加入 ${esc(joined(m.createdAt))} · ${m.enabled ? '启用' : '停用'}${m.confirmed ? '' : ' · 邮箱未确认'}</small></span><span class="account-row-chevron" aria-hidden="true">›</span></button>`).join('');
   $('members').querySelectorAll('[data-member]').forEach(button=>button.onclick=()=>select(button.dataset.member));loading=false;controls(data.total);void loadPending(ticket,seq);
  }catch(error){if(ticket!==epoch || seq!==listSequence || !visible)return;if(invalid(error))return;loading=false;controls();$('message').textContent=error.message;}
 }
 async function select(id){const ticket=epoch,seq=++detailSequence;selected=id;currentMember=null;$('actions').hidden=true;setExpanded(true);stats.clear();$('identity').replaceChildren();$('detail').hidden=false;$('detail-message').textContent='正在读取该成员的统计…';$('members').querySelectorAll('[data-member]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.member===id)));
  try{const data=await api.memberStatistics(id);if(ticket!==epoch || seq!==detailSequence || selected!==id || !visible)return;
   if(data.member?.id!==id || !data.snapshot?.statistics)throw new Error('成员统计响应不完整，请重试。');
   const m=data.member;currentMember=m;$('actions').hidden=false;$('coins').disabled=!Number.isSafeInteger(m.balance);$('identity').innerHTML=`<strong>${esc(m.email)}</strong><p class="dialog-note">${m.enabled ? '启用' : '停用'} · 加入 ${esc(joined(m.createdAt))}<br>金币余额：${Number.isSafeInteger(m.balance) ? m.balance : '—'}<br>账户时区：${esc(m.timezone || '尚未设置（空账户暂按 UTC）')} · 数据日期：${esc(data.snapshot.today)}</p>`;
   $('detail-message').textContent='只读统计，不修改该成员的打卡或金币。';stats.update(data.snapshot);
  }catch(error){if(ticket!==epoch || seq!==detailSequence || selected!==id || !visible)return;if(invalid(error))return;$('detail-message').textContent=error.message;}
 }
 async function loadPending(ticket,seq){if(!api.pendingMemberWrites)return;try{const data=await api.pendingMemberWrites();if(ticket!==epoch || seq!==listSequence || !visible)return;const jobs=data.jobs || [];$('pending').hidden=!jobs.length;$('pending').innerHTML=jobs.length ? `<h3>待确认操作</h3><p>上次请求的结果尚未确认。稍后继续同一次操作，需重新输入原先填写的新密码。</p>${jobs.map((j,i)=>`<button type="button" data-resume="${i}">${esc(j.email)} · ${esc({'member-create':'新增账号','member-password':'修改密码','member-delete':'删除账号'}[j.operation])}</button>`).join('')}` : '';$('pending').querySelectorAll('[data-resume]').forEach(b=>b.onclick=()=>{const j=jobs[Number(b.dataset.resume)],mode={'member-create':'create','member-password':'password','member-delete':'delete'}[j.operation];editor.open(mode,{id:j.memberId,email:j.email},j);});}catch(error){if(ticket===epoch && visible){if(invalid(error))return;$('message').textContent+=' 待确认操作读取失败，请刷新重试。';}}}
 function clear(){editor.clear();$('operation-message').textContent='';$('pending').replaceChildren();$('pending').hidden=true;++epoch;++listSequence;loading=false;clearDetail();$('members').replaceChildren();$('message').textContent='';$('page-label').textContent='';controls();}
 $('add').onclick=()=>editor.open('create');$('password').onclick=()=>currentMember && editor.open('password',currentMember);$('coins').onclick=()=>currentMember && editor.open('coins',currentMember);$('delete').onclick=()=>currentMember && editor.open('delete',currentMember);
 $('search-form').onsubmit=event=>{event.preventDefault();search=$('search').value.trim();page=1;void load();};$('refresh').onclick=()=>void load();$('prev').onclick=()=>{page--;void load();};$('next').onclick=()=>{page++;void load();};$('toggle').onclick=()=>setExpanded($('detail-body').hidden);
 return {busy:()=>editor.busy(),show(){if(visible)return;visible=true;void load();},hide(){visible=false;clear();},clear(){visible=false;page=1;search='';$('search').value='';clear();}};
}
